// Generated by Apple Swift version 4.0.2 effective-3.2.2 (swiftlang-900.0.69.2 clang-900.0.38)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

SWIFT_MODULE_NAMESPACE_PUSH("DriveQuant_SDK")

SWIFT_CLASS("_TtC14DriveQuant_SDK7Account")
@interface Account : NSObject
@property (nonatomic, copy) NSString * _Nonnull account;
@property (nonatomic, copy) NSString * _Nonnull userId;
@property (nonatomic, copy) NSString * _Nullable deviceId;
@property (nonatomic, copy) NSString * _Nullable password;
- (nonnull instancetype)initWithAccount:(NSString * _Nonnull)account userId:(NSString * _Nonnull)userId OBJC_DESIGNATED_INITIALIZER;
- (NSDictionary<NSString *, id> * _Nonnull)getJSON SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class EcoDrivingContext;

SWIFT_CLASS("_TtC14DriveQuant_SDK18AdvancedEcoDriving")
@interface AdvancedEcoDriving : NSObject
@property (nonatomic, copy) NSArray<EcoDrivingContext *> * _Nullable ecoDrivingContext;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class FuelEstimationContext;

SWIFT_CLASS("_TtC14DriveQuant_SDK22AdvancedFuelEstimation")
@interface AdvancedFuelEstimation : NSObject
@property (nonatomic, copy) NSArray<FuelEstimationContext *> * _Nullable fuelEstimationContext;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class SafetyContext;

SWIFT_CLASS("_TtC14DriveQuant_SDK14AdvancedSafety")
@interface AdvancedSafety : NSObject
@property (nonatomic, copy) NSArray<SafetyContext *> * _Nullable safetyContext;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class PostGenericResponse;
@class Route;
@class ItineraryData;

SWIFT_PROTOCOL("_TtP14DriveQuant_SDK18DriveQuantProtocol_")
@protocol DriveQuantProtocol
- (void)handleRepostResult:(PostGenericResponse * _Nullable)response route:(Route * _Nonnull)route itineraryData:(ItineraryData * _Nonnull)itineraryData;
@end

@class Vehicle;
@protocol PostGenericProtocol;
@class NSString;

SWIFT_CLASS("_TtC14DriveQuant_SDK22DriveQuantTripAnalysis")
@interface DriveQuantTripAnalysis : NSObject
- (void)setVehicle:(Vehicle * _Nonnull)vehicle;
+ (void)initializeSDK:(Account * _Nonnull)account listener:(id <DriveQuantProtocol> _Nonnull)listener;
+ (void)activateAutoStart:(id <PostGenericProtocol> _Nonnull)listener userId:(NSString * _Nonnull)userId vehicle:(Vehicle * _Nonnull)vehicle;
+ (void)deactivateAutoStart;
+ (BOOL)start:(id <PostGenericProtocol> _Nonnull)listener vehicle:(Vehicle * _Nonnull)vehicle SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)stop SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isTripRunning SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC14DriveQuant_SDK10EcoDriving")
@interface EcoDriving : NSObject
@property (nonatomic) double score;
@property (nonatomic) double scoreAccel;
@property (nonatomic) double scoreMain;
@property (nonatomic) double scoreDecel;
@property (nonatomic) double stdDevAccel;
@property (nonatomic) double stdDevMain;
@property (nonatomic) double stdDevDecel;
@property (nonatomic) NSInteger energyClass;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC14DriveQuant_SDK17EcoDrivingContext")
@interface EcoDrivingContext : NSObject
@property (nonatomic) NSInteger contextId;
@property (nonatomic) double distance;
@property (nonatomic) double duration;
@property (nonatomic) double efficiencyScore;
@property (nonatomic) double scoreAccel;
@property (nonatomic) double scoreMain;
@property (nonatomic) double scoreDecel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC14DriveQuant_SDK14FuelEstimation")
@interface FuelEstimation : NSObject
@property (nonatomic) double co2Mass;
@property (nonatomic) double co2Emission;
@property (nonatomic) double fuelVolume;
@property (nonatomic) double fuelConsumption;
@property (nonatomic) double idleFuelVolume;
@property (nonatomic) double idleFuelPercentage;
@property (nonatomic) double idleFuelConsumption;
@property (nonatomic) double idleCo2Emission;
@property (nonatomic) double idleCo2Mass;
@property (nonatomic) BOOL engineTempStatus;
@property (nonatomic) double coldFuelVolume;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC14DriveQuant_SDK21FuelEstimationContext")
@interface FuelEstimationContext : NSObject
@property (nonatomic) double co2Mass;
@property (nonatomic) double co2Emission;
@property (nonatomic) double fuelVolume;
@property (nonatomic) double fuelConsumption;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC14DriveQuant_SDK13ItineraryData")
@interface ItineraryData : NSObject
@property (nonatomic, copy) NSString * _Nullable endDate;
@property (nonatomic, copy) NSString * _Nullable departureCity;
@property (nonatomic, copy) NSString * _Nullable arrivalCity;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable weatherCode;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable weatherIndex;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSDictionary<NSString *, id> * _Nonnull)getJSON SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14DriveQuant_SDK19ItineraryStatistics")
@interface ItineraryStatistics : NSObject
@property (nonatomic) double tripDuration;
@property (nonatomic) double drivingDuration;
@property (nonatomic) double idlingDuration;
@property (nonatomic) double drivingPercentage;
@property (nonatomic) double idlingPercentage;
@property (nonatomic) double distance;
@property (nonatomic) double speedMean;
@property (nonatomic) NSInteger subdispNb;
@property (nonatomic) NSInteger meteo;
@property (nonatomic) BOOL day;
@property (nonatomic) BOOL weekDay;
@property (nonatomic) NSInteger transportationMode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end



@class RouteData;

SWIFT_PROTOCOL("_TtP14DriveQuant_SDK19PostGenericProtocol_")
@protocol PostGenericProtocol
- (void)handleResult:(BOOL)status response:(PostGenericResponse * _Nullable)response route:(Route * _Nonnull)route itineraryData:(ItineraryData * _Nonnull)itineraryData;
- (void)handleRouteData:(double)distance speed:(double)speed accel:(double)accel maintain:(double)maintain decel:(double)decel efficiency:(double)efficiency recommendedGearbox:(NSInteger)recommendedGearbox duration:(double)duration speedMean:(double)speedMean co2:(double)co2 energyClass:(NSInteger)energyClass longitude:(double)longitude latitude:(double)latitude gpsElevation:(double)gpsElevation gpsAccuracy:(double)gpsAccuracy gpsHeading:(double)gpsHeading;
- (void)handleRouteDataWithRouteData:(RouteData * _Nonnull)routeData;
- (void)autoTripStarted;
@end

@class Safety;

SWIFT_CLASS("_TtC14DriveQuant_SDK19PostGenericResponse")
@interface PostGenericResponse : NSObject
@property (nonatomic, copy) NSString * _Nullable itinId;
@property (nonatomic, strong) Account * _Nullable account;
@property (nonatomic, strong) ItineraryStatistics * _Nullable itineraryStatistics;
@property (nonatomic, strong) EcoDriving * _Nullable ecoDriving;
@property (nonatomic, strong) FuelEstimation * _Nullable fuelEstimation;
@property (nonatomic, strong) Safety * _Nullable safety;
@property (nonatomic, strong) AdvancedEcoDriving * _Nullable advancedEcoDriving;
@property (nonatomic, strong) AdvancedFuelEstimation * _Nullable advancedFuelEstimation;
@property (nonatomic, strong) AdvancedSafety * _Nullable advancedSafety;
@property (nonatomic, copy) NSString * _Nonnull endDate;
@property (nonatomic, strong) ItineraryData * _Nullable itineraryData;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC14DriveQuant_SDK5Route")
@interface Route : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (id _Nonnull)getGpsVelocity SWIFT_WARN_UNUSED_RESULT;
- (void)setGpsVelocity:(NSArray<NSNumber *> * _Nonnull)gpsVelocity;
- (id _Nonnull)getLatitude SWIFT_WARN_UNUSED_RESULT;
- (void)setLatitude:(NSArray<NSNumber *> * _Nonnull)latitude;
- (id _Nonnull)getAltitude SWIFT_WARN_UNUSED_RESULT;
- (void)setAltitude:(NSArray<NSNumber *> * _Nonnull)altitude;
- (id _Nonnull)getLongitude SWIFT_WARN_UNUSED_RESULT;
- (void)setLongitude:(NSArray<NSNumber *> * _Nonnull)longitude;
- (void)setGpsAccuracy:(NSArray<NSNumber *> * _Nonnull)gpsAccuracy;
- (id _Nonnull)getGpsAccuracy SWIFT_WARN_UNUSED_RESULT;
- (void)setGpsHeading:(NSArray<NSNumber *> * _Nonnull)gpsHeading;
- (id _Nonnull)getGpsHeading SWIFT_WARN_UNUSED_RESULT;
- (void)setGpsDate:(NSArray<NSNumber *> * _Nonnull)gpsDate;
- (id _Nonnull)getGpsDate SWIFT_WARN_UNUSED_RESULT;
- (void)setVehVelocity:(NSArray<NSNumber *> * _Nonnull)vehVelocity;
- (id _Nonnull)getVehVelocity SWIFT_WARN_UNUSED_RESULT;
- (void)setVehEngineSpeed:(NSArray<NSNumber *> * _Nonnull)vehEngineSpeed;
- (id _Nonnull)getVehEngineSpeed SWIFT_WARN_UNUSED_RESULT;
- (void)setVehTankLevel:(NSArray<NSNumber *> * _Nonnull)vehTankLevel;
- (id _Nonnull)getVehTankLevel SWIFT_WARN_UNUSED_RESULT;
- (void)setVehWheelAngle:(NSArray<NSNumber *> * _Nonnull)vehWheelAngle;
- (id _Nonnull)getVehWheelAngle SWIFT_WARN_UNUSED_RESULT;
- (void)setVehDate:(NSArray<NSNumber *> * _Nonnull)vehDate;
- (id _Nonnull)getVehDate SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14DriveQuant_SDK9RouteData")
@interface RouteData : NSObject
@property (nonatomic) double distance;
@property (nonatomic) double speed;
@property (nonatomic) double accel;
@property (nonatomic) double maintain;
@property (nonatomic) double decel;
@property (nonatomic) double efficiency;
@property (nonatomic) NSInteger recommendedGearbox;
@property (nonatomic) double duration;
@property (nonatomic) double speedMean;
@property (nonatomic) double co2;
@property (nonatomic) double co2Opti;
@property (nonatomic) NSInteger energyClass;
@property (nonatomic) double longitude;
@property (nonatomic) double latitude;
@property (nonatomic) double gpsElevation;
@property (nonatomic) double gpsAccuracy;
@property (nonatomic) double gpsHeading;
@property (nonatomic) NSInteger ringMin;
@property (nonatomic) NSInteger ringMax;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14DriveQuant_SDK6Safety")
@interface Safety : NSObject
@property (nonatomic) NSInteger nbAdh;
@property (nonatomic) NSInteger nbAccel;
@property (nonatomic) NSInteger nbDecel;
@property (nonatomic) NSInteger nbAdhCrit;
@property (nonatomic) NSInteger nbAccelCrit;
@property (nonatomic) NSInteger nbDecelCrit;
@property (nonatomic) double safetyScore;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC14DriveQuant_SDK13SafetyContext")
@interface SafetyContext : NSObject
@property (nonatomic) NSInteger contextId;
@property (nonatomic) double distance;
@property (nonatomic) double duration;
@property (nonatomic) NSInteger nbAdh;
@property (nonatomic) NSInteger nbAccel;
@property (nonatomic) NSInteger nbDecel;
@property (nonatomic) NSInteger nbAdhCrit;
@property (nonatomic) NSInteger nbAccelCrit;
@property (nonatomic) NSInteger nbDecelCrit;
@property (nonatomic) double safetyScore;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface UIDevice (SWIFT_EXTENSION(DriveQuant_SDK))
@property (nonatomic, readonly, copy) NSString * _Nonnull modelName;
@end


SWIFT_CLASS("_TtC14DriveQuant_SDK7Vehicle")
@interface Vehicle : NSObject
@property (nonatomic) NSInteger carTypeIndex;
@property (nonatomic) NSInteger carEngineIndex;
@property (nonatomic) double carPower;
@property (nonatomic) double carMass;
@property (nonatomic) NSInteger carGearboxIndex;
@property (nonatomic) double carConsumption;
@property (nonatomic) NSInteger carAutoGearboxNumber;
@property (nonatomic) double engineDisplacement;
@property (nonatomic) double declaredCarConsumption;
@property (nonatomic) NSInteger carPassengers;
@property (nonatomic, copy) NSString * _Nonnull sra;
@property (nonatomic, copy) NSString * _Nonnull dqIndex;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSDictionary<NSString *, id> * _Nonnull)getJSON SWIFT_WARN_UNUSED_RESULT;
+ (Vehicle * _Nonnull)defaultVehicle SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
